signIn:
    path: /signIn
    defaults: { _controller: AppBundle:Default:signIn }

profile:
    path: /profile
    defaults: { _controller: AppBundle:Default:profile }

signUp:
    path: /signUp
    defaults: { _controller: AppBundle:Default:signUp }
    
uploadFile:
    path: /uploadFile
    defaults: { _controller: AppBundle:Default:uploadFile }

check:
    path: /check
logout:
    path: /logout
    